// import type { Metadata } from "next";
// import { Fira_Code,  } from "next/font/google";
// import "./globals.css";
// import Navbar from "./Components/Navbar";
// import ThProvider from "./Utils/ThProvider";



// const fira = Fira_Code({ subsets: ["latin"]});

// // Removed Geist_Mono as it is not exported by the module

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${fira.className}  `}
//       >
//         <ThProvider>
//         <Navbar/>
//         <main className="max-w-4xl mx-auto px-6">
//         {children}
//         </main>
//         </ThProvider>
//       </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import ThProvider from "../Utils/ThProvider";
import Navbar from "../Components/Navbar";


const firaCode = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${firaCode.className} h-full bg-amber-50 text-gray-800 dark:bg-slate-950 dark:text-amber-50 dark:selection:bg-white `}
      >
        {/*bg-amber-50 text-indigo-950 dark:bg-slate-950 dark:text-amber-50 dark:selection:bg-purple-500 */}
        <ThProvider>
          <Navbar />
          <main className="h-full mx-auto max-w-4xl px-6">{children}</main>
        </ThProvider>
      </body>
    </html>
  );
}